name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploying:
    name: Deploy Application to Staging Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH and Deploy
        run: |
          echo "${{ secrets.SSH_PVT_KEY }}" > ssh_key
          chmod 600 ssh_key

          ssh -o StrictHostKeyChecking=no -i ssh_key ubuntu@13.203.102.221 << 'EOF'
            cd /home/ubuntu/bookMyShow
            git pull origin main
            pnpm install
            pnpm run build
            pm2 restart all
          EOF
