name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploying:
    runs-on: ubuntu-latest
    name: Deploy Application to Staging Environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH and Deploy
        run: |
          echo "${{ secrets.SSH_PVT_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          
          mkdir -p ~/.ssh
          chmod 700 /home/runner/ssh_key
          touch ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          
          ssh-keyscan -H 13.203.102.221 >> ~/.ssh/known_hosts

          ssh -i ~/ssh_key -o StrictHostKeyChecking=no ubuntu@13.203.102.221 << 'EOF'
            cd /home/ubuntu/bookMyShow
            git pull origin main
            pnpm install
            pnpm run build
            pm2 restart all
          EOF
          
          rm -f ~/ssh_key
