jobs:
  deploying:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H 13.203.102.221 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Write SSH Key
        run: |
          echo "${{ secrets.SSH_PVT_KEY }}" | tr -d '\r' > ssh_key
          chmod 600 ssh_key

      - name: Deploy to EC2
        run: |
          ssh -v -i ssh_key -o StrictHostKeyChecking=no ubuntu@13.203.102.221 << 'EOF'
            cd /home/ubuntu/bookMyShow
            git pull origin main
            pnpm install
            pnpm run build
            pm2 restart all
          EOF
